# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: environments/data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65nvironments/data.proto\"i\n\x07NDArray\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x05\x12\r\n\x05\x64type\x18\x02 \x01(\t\x12\x14\n\x0c\x66loat_values\x18\x03 \x03(\x02\x12\x15\n\rdouble_values\x18\x04 \x03(\x01\x12\x14\n\x0cint64_values\x18\x05 \x03(\x03\"Z\n\x07\x42oxInfo\x12\x17\n\x05spans\x18\x01 \x01(\x0b\x32\x08.NDArray\x12\x1a\n\x08\x63\x65ntroid\x18\x02 \x01(\x0b\x32\x08.NDArray\x12\x1a\n\x08rotation\x18\x03 \x01(\x0b\x32\x08.NDArray\")\n\tTargetSet\x12\x1c\n\x07targets\x18\x01 \x03(\x0b\x32\x0b.TargetInfo\"D\n\nTargetInfo\x12\x1a\n\x08position\x18\x01 \x01(\x0b\x32\x08.NDArray\x12\x1a\n\x08rotation\x18\x02 \x01(\x0b\x32\x08.NDArray\"F\n\x0fPredefinedTasks\x12\x12\n\nworld_path\x18\x01 \x01(\t\x12\x1f\n\x0btarget_sets\x18\x02 \x03(\x0b\x32\n.TargetSet\"\xad\x01\n\nStartState\x12%\n\x13generated_obstacles\x18\x01 \x03(\x0b\x32\x08.BoxInfo\x12\x1c\n\x07targets\x18\x02 \x03(\x0b\x32\x0b.TargetInfo\x12.\n\x1cinitial_joint_configurations\x18\x03 \x01(\x0b\x32\x08.NDArray\x12*\n\x18initial_robot_placements\x18\x04 \x01(\x0b\x32\x08.NDArray\"0\n\x0bStartStates\x12!\n\x0cstart_states\x18\x01 \x03(\x0b\x32\x0b.StartState\"R\n\x0bPyTreeEntry\x12\x1a\n\x07subtree\x18\x01 \x01(\x0b\x32\x07.PyTreeH\x00\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\x08.NDArrayH\x00\x42\x0c\n\nentry_type\"5\n\x06PyTree\x12\x0c\n\x04keys\x18\x01 \x03(\t\x12\x1d\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x0c.PyTreeEntry\"\xa1\x01\n\nTransition\x12#\n\x12scaled_observation\x18\x01 \x01(\x0b\x32\x07.PyTree\x12\x1f\n\rscaled_action\x18\x02 \x01(\x0b\x32\x08.NDArray\x12(\n\x17scaled_next_observation\x18\x03 \x01(\x0b\x32\x07.PyTree\x12\x0e\n\x06reward\x18\x04 \x01(\x02\x12\x13\n\x0bis_terminal\x18\x05 \x01(\x08\x62\x06proto3')



_NDARRAY = DESCRIPTOR.message_types_by_name['NDArray']
_BOXINFO = DESCRIPTOR.message_types_by_name['BoxInfo']
_TARGETSET = DESCRIPTOR.message_types_by_name['TargetSet']
_TARGETINFO = DESCRIPTOR.message_types_by_name['TargetInfo']
_PREDEFINEDTASKS = DESCRIPTOR.message_types_by_name['PredefinedTasks']
_STARTSTATE = DESCRIPTOR.message_types_by_name['StartState']
_STARTSTATES = DESCRIPTOR.message_types_by_name['StartStates']
_PYTREEENTRY = DESCRIPTOR.message_types_by_name['PyTreeEntry']
_PYTREE = DESCRIPTOR.message_types_by_name['PyTree']
_TRANSITION = DESCRIPTOR.message_types_by_name['Transition']
NDArray = _reflection.GeneratedProtocolMessageType('NDArray', (_message.Message,), {
  'DESCRIPTOR' : _NDARRAY,
  '__module__' : 'environments.data_pb2'
  # @@protoc_insertion_point(class_scope:NDArray)
  })
_sym_db.RegisterMessage(NDArray)

BoxInfo = _reflection.GeneratedProtocolMessageType('BoxInfo', (_message.Message,), {
  'DESCRIPTOR' : _BOXINFO,
  '__module__' : 'environments.data_pb2'
  # @@protoc_insertion_point(class_scope:BoxInfo)
  })
_sym_db.RegisterMessage(BoxInfo)

TargetSet = _reflection.GeneratedProtocolMessageType('TargetSet', (_message.Message,), {
  'DESCRIPTOR' : _TARGETSET,
  '__module__' : 'environments.data_pb2'
  # @@protoc_insertion_point(class_scope:TargetSet)
  })
_sym_db.RegisterMessage(TargetSet)

TargetInfo = _reflection.GeneratedProtocolMessageType('TargetInfo', (_message.Message,), {
  'DESCRIPTOR' : _TARGETINFO,
  '__module__' : 'environments.data_pb2'
  # @@protoc_insertion_point(class_scope:TargetInfo)
  })
_sym_db.RegisterMessage(TargetInfo)

PredefinedTasks = _reflection.GeneratedProtocolMessageType('PredefinedTasks', (_message.Message,), {
  'DESCRIPTOR' : _PREDEFINEDTASKS,
  '__module__' : 'environments.data_pb2'
  # @@protoc_insertion_point(class_scope:PredefinedTasks)
  })
_sym_db.RegisterMessage(PredefinedTasks)

StartState = _reflection.GeneratedProtocolMessageType('StartState', (_message.Message,), {
  'DESCRIPTOR' : _STARTSTATE,
  '__module__' : 'environments.data_pb2'
  # @@protoc_insertion_point(class_scope:StartState)
  })
_sym_db.RegisterMessage(StartState)

StartStates = _reflection.GeneratedProtocolMessageType('StartStates', (_message.Message,), {
  'DESCRIPTOR' : _STARTSTATES,
  '__module__' : 'environments.data_pb2'
  # @@protoc_insertion_point(class_scope:StartStates)
  })
_sym_db.RegisterMessage(StartStates)

PyTreeEntry = _reflection.GeneratedProtocolMessageType('PyTreeEntry', (_message.Message,), {
  'DESCRIPTOR' : _PYTREEENTRY,
  '__module__' : 'environments.data_pb2'
  # @@protoc_insertion_point(class_scope:PyTreeEntry)
  })
_sym_db.RegisterMessage(PyTreeEntry)

PyTree = _reflection.GeneratedProtocolMessageType('PyTree', (_message.Message,), {
  'DESCRIPTOR' : _PYTREE,
  '__module__' : 'environments.data_pb2'
  # @@protoc_insertion_point(class_scope:PyTree)
  })
_sym_db.RegisterMessage(PyTree)

Transition = _reflection.GeneratedProtocolMessageType('Transition', (_message.Message,), {
  'DESCRIPTOR' : _TRANSITION,
  '__module__' : 'environments.data_pb2'
  # @@protoc_insertion_point(class_scope:Transition)
  })
_sym_db.RegisterMessage(Transition)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NDARRAY._serialized_start=27
  _NDARRAY._serialized_end=132
  _BOXINFO._serialized_start=134
  _BOXINFO._serialized_end=224
  _TARGETSET._serialized_start=226
  _TARGETSET._serialized_end=267
  _TARGETINFO._serialized_start=269
  _TARGETINFO._serialized_end=337
  _PREDEFINEDTASKS._serialized_start=339
  _PREDEFINEDTASKS._serialized_end=409
  _STARTSTATE._serialized_start=412
  _STARTSTATE._serialized_end=585
  _STARTSTATES._serialized_start=587
  _STARTSTATES._serialized_end=635
  _PYTREEENTRY._serialized_start=637
  _PYTREEENTRY._serialized_end=719
  _PYTREE._serialized_start=721
  _PYTREE._serialized_end=774
  _TRANSITION._serialized_start=777
  _TRANSITION._serialized_end=938
# @@protoc_insertion_point(module_scope)
