# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Environment implementation for path planning."""

from collections.abc import Mapping, Sequence
import copy
import dataclasses
import functools
import itertools
import math
import random
import re

import dm_env
from dm_env import specs
from flax import struct
import numpy as np
from scipy.spatial import transform as transform_lib

from environments import base_env
from environments import data_pb2
from environments import geometry
from environments import mujoco_simulator
from environments import target
from environments import util


# How many times to try sampling an obstacle box.
_MAX_OBSTACLE_SAMPLING_ATTEMPTS = 100

# How far targets are offset from surfaces.
_TARGET_SURFACE_OFFSET = 0.03

# The direction the robot is facing in the robot frame.
_ROBOT_FACING_DIRECTION_LOCAL = np.array([1.0, 0.0, 0.0], dtype=np.float32)

# Floating point comparison epsilon.
_EPSILON = 1e-3

_GENERATED_OBSTACLE_COLOUR = np.array([0.4, 0.4, 0.4], dtype=np.float32)

# During obstacle generation, we need to be able to move boxes out of the way.
# This is where "out of the way" is.
_FAR_AWAY = 1000.0


SpecTree = Mapping[str, 'SpecTree | specs.BoundedArray']
ArrayTree = Mapping[str, 'ArrayTree | np.ndarray']


class InvalidStartStateError(Exception):
  """Raised when the start state is invalid."""


def _make_pose(position: np.ndarray, rotation: np.ndarray | None) -> np.ndarray:
  """Returns a pose matrix from position and rotation."""
  if len(position.shape) == 1:
    pose = np.eye(4, dtype=position.dtype)
    pose[:3, :3] = rotation
    pose[:3, 3] = position
  else:
    batch_size = position.shape[0]
    pose = np.eye(4, dtype=position.dtype)
    pose = np.tile(pose, (batch_size, 1, 1))
    pose[:, :3, :3] = rotation
    pose[:, :3, 3] = position
  return pose


def _move_robot_along_axis(
    world: mujoco_simulator.MujocoWorld,
    robot_name: str,
    axis: str,
    new_coordinate: float,
) -> None:
  """Moves a robot to a new coordinate along the given axis."""
  transform = world.GetWorldTransform(robot_name)

  if axis == 'x':
    transform[0, 3] = new_coordinate  # Column 3 is translation, 0 is x-axis.
  elif axis == 'y':
    transform[1, 3] = new_coordinate  # Column 3 is translation, 1 is y-axis.
  elif axis == 'z':
    transform[2, 3] = new_coordinate  # Column 3 is translation, 2 is z-axis.
  else:
    raise ValueError(f'Unsupported axis: {axis}')

  world.SetWorldTransform(robot_name, transform)


def _is_monotonically_decreasing(x: Sequence[float]):
  """Returns whether a sequence is monotonically decreasing."""
  for i in range(len(x) - 1):
    if x[i] < x[i + 1]:
      return False
  return True


class Range(struct.PyTreeNode):
  """Represents an arbitrary-dimensional range."""

  mins: np.ndarray
  maxs: np.ndarray


class PlanningEnvConfig(struct.PyTreeNode):
  """Planning environment configuration.

  Attributes:
      base_config: Config for the base environment.
      num_obstacles_to_generate: Number of boxes to generate as obstacles.
      obstacle_spans_range: Obstacle dimensions range to sample from.
      obstacle_position_range: Obstacle centres to sample from.
      obstacles_by_decomposition: Obstacles to be generated by decomposing
          objects already in the world. Each key is an object ID, and the value
        is
        the number of decomposed obstacles.
      num_targets_to_generate: Number of targets to generate.
      targets_have_orientation: Whether targets have orientation (or
        position-only).
      target_obj_filter: Regex to determine which objects to sample targets on.
      target_pose_max_angle_from_normal_rad: Maximum angle between sampled
        target poses and inward surface normal.
      dwell_time_s: How much time to freeze robots for after solving a target.
      fixed_targets: Fixed targets to be added to the generated targets.
      target_scoring_config: Config for how targets are scored.
      randomize_robot_placement: If true, randomly place each robot on a circle
        around the origin, with random facing direction.
      randomize_robot_placement_axis: Axis for randomiing robot placement. Valid
        values: 'x', 'y'.
      randomize_robot_placement_min: Minimum coordinate for robot placement.
        robot placement.
      return_to_start_reward_weight: Reward weight for returning to start.
      return_to_start_joint_config_diff_threshold: The joint configuration
        difference threshold for returning to start. Within this threshold, the
        hand-coded return-to-start-pose controller takes over to drive the last
        mile.
      return_to_start_shaped_reward_coefficient: The shaped reward coefficient
        for returning to start.
      return_to_start_required: Whether returning to start is required to finish
        the episode.
      collision_feature_margins: Obsolete. Remove after Science Robotics.
      collision_penalty_scaling: Scaling for collision penalty (only used if
        collisions are allowed). 0 corresponds to no collision penalty, and 1
        corresponds to 1/N penalty for an arm that is in collision for the whole
        episode (scaled by fraction of episode that arm is in collision).
      acceleration_cost: Cost for acceleration.
      augment_obstacle_observations: Whether to augment the obstacle
        representations with random rotations.
      starting_joint_config: Starting joint configuration for the robots.
      verify_targets_have_ik_solutions: Whether to verify that all targets have
        IK solutions.
  """

  base_config: base_env.BaseEnvConfig

  # Obstacle generation.
  num_obstacles_to_generate: int
  obstacle_spans_range: Range = dataclasses.field(
      default_factory=lambda: Range(
          mins=np.array([0.02, 0.02, 0.1]), maxs=np.array([0.05, 0.05, 0.6])
      )
  )
  obstacle_position_range: Range = dataclasses.field(
      default_factory=lambda: Range(
          mins=np.array([-0.3, -0.3, 0.0]), maxs=np.array([0.3, 0.3, 1.2])
      )
  )
  obstacles_by_decomposition: dict[str, int] = dataclasses.field(
      default_factory=dict
  )
  # Target sampling.
  num_targets_to_generate: int = 10
  targets_have_orientation: bool = True
  target_obj_filter: str = 'box_(.*)'
  target_pose_max_angle_from_normal_rad: float = np.pi / 8.0
  dwell_time_s: float = 0.5

  # Fixed targets.
  fixed_targets: list[target.TargetInfo] = dataclasses.field(
      default_factory=list
  )

  # Scoring and rewards.
  target_scoring_config: target.TargetScoringConfig = dataclasses.field(
      default_factory=target.TargetScoringConfig
  )

  randomize_robot_placement: bool = True
  randomize_robot_placement_axis: str = 'y'
  randomize_robot_placement_min: float = -0.8
  randomize_robot_placement_max: float = 0.8

  return_to_start_reward_weight: float = 0.25
  return_to_start_joint_config_diff_threshold: float = 0.25

  # Return to start shaped reward is:
  # 1 - c * max(mse(qpos, start_qpos), 0)
  return_to_start_shaped_reward_coefficient: float = 3.0

  return_to_start_required: bool = True

  collision_feature_margins: list[float] = dataclasses.field(
      default_factory=lambda: []
  )

  collision_penalty_scaling: float = 15.0

  acceleration_cost: float = 0.0
  augment_obstacle_observations: bool = True

  starting_joint_config: list[np.ndarray] = dataclasses.field(
      default_factory=list
  )

  verify_targets_have_ik_solutions: bool = True


@dataclasses.dataclass(frozen=True)
class BoxInfo:
  """Info for a generated obstacle box or OBB."""

  spans: np.ndarray  # (3,)
  centroid: np.ndarray  # (3,)
  rotation: np.ndarray  # (3,3)

  def __eq__(self, other):
    if type(other) is type(self):
      return (
          np.allclose(self.spans, other.spans)
          and np.allclose(self.centroid, other.centroid)
          and np.allclose(self.rotation, other.rotation)
      )
    return False

  def to_proto(self) -> data_pb2.BoxInfo:
    return data_pb2.BoxInfo(
        spans=util.to_proto(self.spans),
        centroid=util.to_proto(self.centroid),
        rotation=util.to_proto(self.rotation),
    )

  @classmethod
  def from_proto(cls, proto: data_pb2.BoxInfo):
    return cls(
        spans=util.from_proto(proto.spans),
        centroid=util.from_proto(proto.centroid),
        rotation=util.from_proto(proto.rotation),
    )

  def get_augmentation(self, aug_selection: int) -> 'BoxInfo':
    """Returns an augmented version of the box.

    Each BoxInfo has 4 possible augmentations (aug_selection):
      0: No augmentation.
      1: Rotated 90 degrees around x-axis.
      2: Rotated 90 degrees around y-axis.
      3: Rotated 90 degrees around z-axis.

    Args:
      aug_selection: The index of the augmentation to apply.

    Returns:
      The augmented BoxInfo.
    """
    assert aug_selection in range(4)
    new_spans = self.spans
    rotation_axis = 0
    if aug_selection == 0:
      return self
    elif aug_selection == 1:
      # Rotate around x-axis. Swap y/z.
      new_spans = self.spans[[0, 2, 1]]
      rotation_axis = 0
    elif aug_selection == 2:
      # Rotate around y-axis. Swap x/z.
      new_spans = self.spans[[2, 1, 0]]
      rotation_axis = 1
    elif aug_selection == 3:
      # Rotate around z-axis. Swap x/y.
      new_spans = self.spans[[1, 0, 2]]
      rotation_axis = 2
    rotvec = np.array([0, 0, 0], dtype=np.float32)
    rotvec[rotation_axis] = np.pi / 2
    additional_rotation = transform_lib.Rotation.from_rotvec(rotvec).as_matrix()
    new_rotation = self.rotation @ additional_rotation
    return BoxInfo(
        spans=new_spans,
        centroid=self.centroid,
        rotation=new_rotation,
    )


@dataclasses.dataclass(frozen=True)
class StartState:
  """Information required to reproduce a start state."""

  generated_obstacles: list[BoxInfo]
  targets: list[target.TargetInfo]
  initial_joint_configurations: np.ndarray
  initial_robot_placements: np.ndarray

  def to_proto(self) -> data_pb2.StartState:
    """Converts start state to proto."""
    proto = data_pb2.StartState()
    for obstacle in self.generated_obstacles:
      proto.generated_obstacles.append(obstacle.to_proto())
    for target_info in self.targets:
      proto.targets.append(target_info.to_proto())
    proto.initial_joint_configurations.CopyFrom(util.to_proto(
        self.initial_joint_configurations
    ))
    proto.initial_robot_placements.CopyFrom(util.to_proto(
        self.initial_robot_placements
    ))
    return proto

  @classmethod
  def from_proto(cls, proto: data_pb2.StartState):
    """Converts start state from proto."""
    obstacles = [
        BoxInfo.from_proto(obstacle) for obstacle in proto.generated_obstacles
    ]
    targets = [target.TargetInfo.from_proto(t) for t in proto.targets]
    return cls(
        generated_obstacles=obstacles,
        targets=targets,
        initial_joint_configurations=util.from_proto(
            proto.initial_joint_configurations
        ),
        initial_robot_placements=util.from_proto(
            proto.initial_robot_placements
        ),
    )


# Convex decomposition is expensive, so we cache it. Currently we assume the
# same named object in the same world path has the same pose and
# decomposition. We have to do an extra world load here because Python doesn't
# support ignoring some arguments for a cached function, so we can't just pass
# a world in (we would get a cache miss for every world). We should get very few
# cache misses so it shouldn't be a problem.
@functools.cache
def decompose_obstacles(
    world_path: str, obj_id: str, num_parts: int
) -> list[BoxInfo]:
  """Decomposes an object into oriented bounding boxes of convex parts."""
  world = base_env.load_world_reference_cached(world_path)
  assert obj_id in world.GetObjects()
  meshes = world.GetMeshes(obj_id)
  decomposition = []
  for mesh in meshes:
    convex_hulls = geometry.convex_decomposition(
        vertices=mesh.vertices, faces=mesh.faces, max_parts=num_parts
    )
    for hull in convex_hulls:
      vertices, _ = hull
      obb = geometry.obb_from_points(vertices)
      decomposition.append(
          BoxInfo(
              spans=obb.spans,
              centroid=obb.pose[:3, 3],
              rotation=obb.pose[:3, :3],
          )
      )
  return decomposition


class PlanningEnv(base_env.BaseEnv):
  """This class extends GizaBaseEnv to provide obstacle and target generation."""

  def __init__(
      self,
      config: PlanningEnvConfig,
      start_state: StartState | None = None,
  ):
    super().__init__(config=config.base_config)
    self._planning_config = config

    # This includes both generated training obstacles and decomposed static
    # obstacles.
    self._generated_obstacles: list[tuple[str, BoxInfo]] = []

    self._targets: list[tuple[target.TargetInfo, target.TargetState]] = []
    self._current_score = 0.0
    self._start_state = start_state
    self._dwell_steps_left_by_robot: list[int] = []
    self._dwell_steps = math.ceil(
        config.dwell_time_s / config.base_config.timestep_s
    )

    assert not self._start_state or not config.fixed_targets

    # Obtain starting joint config for robots.
    if config.starting_joint_config:
      self._start_joint_config = config.starting_joint_config
      assert len(self._start_joint_config) == len(self._robots)
    else:
      self._start_joint_config = [
          self._world.GetJointValues(robots) for robots in self._robots
      ]

    self._static_obstacles: list[BoxInfo] = []
    for obj_id, num_obstacles in config.obstacles_by_decomposition.items():
      self._static_obstacles.extend(
          decompose_obstacles(
              world_path=config.base_config.world_file_path,
              obj_id=obj_id,
              num_parts=num_obstacles,
          )
      )
    self._total_collision_penalty = 0.0
    self._total_collision_robot_steps = 0
    self._total_mean_acceleration = 0.0
    self._total_acceleration_cost = 0.0

  @property
  def world(self) -> mujoco_simulator.MujocoWorld:
    """Returns underlying world."""
    return self._world

  def _random_pose(self, pos_range: Range) -> np.ndarray:
    """Samples a random pose."""
    pose = np.eye(4)
    rotation = geometry.sample_rotation()
    pose[:3, :3] = rotation
    centroid = geometry.sample_array(pos_range.mins, pos_range.maxs)
    pose[:3, 3] = centroid
    return pose

  def _sample_and_add_boxes(self) -> None:
    if self._planning_config.num_obstacles_to_generate == 0:
      return
    consecutive_failures = 0
    boxes_done = 0
    dim_range = self._planning_config.obstacle_spans_range
    position_range = self._planning_config.obstacle_position_range

    free_boxes = []
    boxes_to_remove = []

    out_of_the_way_pose = np.eye(4)
    out_of_the_way_pose[:3, 3] = _FAR_AWAY

    while consecutive_failures < _MAX_OBSTACLE_SAMPLING_ATTEMPTS:
      # Generate boxes in batches. This is much faster for MuJoCo since we need
      # to recompile the model for each box otherwise. If we do a bunch of
      # AddBox calls in a row, the recompilation is deferred until the next call
      # that needs the model.
      if not free_boxes:
        num_boxes_to_generate = (
            self._planning_config.num_obstacles_to_generate - boxes_done)
        for _ in range(num_boxes_to_generate):
          spans = geometry.sample_array(dim_range.mins, dim_range.maxs)
          box_id = self._world.AddBox(spans, color=_GENERATED_OBSTACLE_COLOUR)
          free_boxes.append((spans, box_id))
        # Move all new boxes out of the way.
        for _, box_id in free_boxes:
          self._world.SetWorldTransform(box_id, out_of_the_way_pose)

      spans, box_id = free_boxes.pop()
      world_t_box = self._random_pose(position_range)
      self._world.SetWorldTransform(box_id, world_t_box)
      if not self._robots_in_collision():
        box_info = BoxInfo(spans=spans, centroid=world_t_box[:3, 3],
                           rotation=world_t_box[:3, :3])
        boxes_done += 1
        self._generated_obstacles.append((box_id, box_info))
        consecutive_failures = 0

        if boxes_done == self._planning_config.num_obstacles_to_generate:
          break
      else:
        consecutive_failures += 1
        self._world.SetWorldTransform(box_id, out_of_the_way_pose)
        boxes_to_remove.append(box_id)

    # Remove extra free boxes.
    for box_id in boxes_to_remove + [box_id for _, box_id in free_boxes]:
      self._world.RemoveObject(box_id)

    if boxes_done < self._planning_config.num_obstacles_to_generate:
      raise ValueError(
          f'Failed to add box after {_MAX_OBSTACLE_SAMPLING_ATTEMPTS} attempts.'
      )

  def _has_collision_free_ik_solution(self, pose: np.ndarray) -> bool:
    """Returns whether a target pose has any IK solution."""
    for robot in self._robots:
      if self._has_collision_free_ik_solution_for_robot(pose, robot):
        return True
    return False

  def _has_collision_free_ik_solution_for_robot(
      self, pose: np.ndarray, robot: str
  ) -> bool:
    """Returns whether a target pose has any IK solution."""
    original_qpos = self._world.GetJointValues(robot)
    for solution in self._world.ComputeIk(robot, pose, num_solutions=1):
      self._world.SetJointValues(robot, solution)
      if not self._robots_in_collision():
        self._world.SetJointValues(robot, original_qpos)
        return True
    self._world.SetJointValues(robot, original_qpos)
    return False

  def _eligible_objects_for_sampled_targets(self) -> set[str]:
    return {
        obj
        for obj in self._world.GetObjects()
        if re.search(self._planning_config.target_obj_filter, obj)
    }

  def _sample_and_add_target(self) -> None:
    eligible_objs = self._eligible_objects_for_sampled_targets()
    assert eligible_objs, 'No eligible objects for sampled targets.'
    all_triangles = list(
        itertools.chain(
            *[self._world.GetMeshFaces(obj) for obj in eligible_objs]
        )
    )
    triangles_properties = [
        geometry.calculate_triangle_properties(triangle)
        for triangle in all_triangles
    ]
    triangles_areas = [prop.area for prop in triangles_properties]

    # Sample triangles to put targets on weighted by areas.
    sampling_probabilities = geometry.normalize(np.array(triangles_areas))
    sampling_cum_probabilities = np.cumsum(sampling_probabilities)
    while len(self._targets) < self._planning_config.num_targets_to_generate:
      triangle_idx = random.choices(
          population=list(range(len(all_triangles))),
          cum_weights=sampling_cum_probabilities,
      )[0]
      triangle_properties = triangles_properties[triangle_idx]
      inward_normal = -triangle_properties.normal
      target_position = geometry.sample_point_from_triangle(
          all_triangles[triangle_idx]
      ) - (_TARGET_SURFACE_OFFSET * inward_normal)
      target_orientation = geometry.sample_frame_with_z_close_to(
          inward_normal,
          self._planning_config.target_pose_max_angle_from_normal_rad,
      )
      target_pose = np.eye(4)
      target_pose[:3, :3] = target_orientation
      target_pose[:3, 3] = target_position
      if self._planning_config.verify_targets_have_ik_solutions:
        if not self._has_collision_free_ik_solution(target_pose):
          continue
      if self._planning_config.targets_have_orientation:
        target_info = target.TargetInfo(
            position=target_position, rotation=target_orientation
        )
      else:
        target_info = target.TargetInfo(position=target_position)
      self._targets.append((target_info, target.TargetState()))

  def _random_move_robot(
      self, robot_name: str, min_val: float, max_val: float, axis: str = 'y'
  ) -> None:
    """Randomly moves a robot.

    The robot is moved randomly along the axis between min and max.

    Args:
      robot_name: object ID of the robot to move.
      min_val: Minimum axis-coordinate.
      max_val: Maximum axis-coordinate.
      axis: Axis to move the robot along.

    Returns:
      None
    """
    while True:
      new_coordinate = np.random.uniform(low=min_val, high=max_val)
      _move_robot_along_axis(
          self._world, robot_name, axis=axis, new_coordinate=new_coordinate
      )

      if not self._robots_in_collision():
        break

  def _randomly_move_robots(self):
    shuffled_robots = copy.copy(self._robots)
    random.shuffle(shuffled_robots)
    for robot in shuffled_robots:
      self._random_move_robot(
          robot_name=robot,
          axis=self._planning_config.randomize_robot_placement_axis,
          min_val=self._planning_config.randomize_robot_placement_min,
          max_val=self._planning_config.randomize_robot_placement_max,
      )

  def _return_to_start_score(self):
    """Calculates return to start score."""
    total = 0.0
    config = self._planning_config
    # c * (pi^2 - mse(qpos_target - qpos_start)) / pi^2
    c = config.return_to_start_shaped_reward_coefficient
    threshold = config.return_to_start_joint_config_diff_threshold
    for robot, start_jnt_config in zip(self._robots, self._start_joint_config):
      qpos = self._world.GetJointValues(robot)
      qpos_diff = np.abs(qpos - start_jnt_config)
      # If all joint values are within the threshold, we get the max score.
      # Otherwise we get a shaped score.
      if (qpos_diff < threshold).all():
        total += 1.0
      else:
        total += 1.0 - np.clip(c * np.mean(qpos_diff**2), 0.0, 1.0)
    return total / len(self._robots)

  def _all_arms_are_parked(self) -> bool:
    """Returns whether all arms are parked back at start pose."""
    for robot, start_jnt_config in zip(self._robots, self._start_joint_config):
      qpos = self._world.GetJointValues(robot)
      qpos_diff = np.abs(qpos - start_jnt_config)
      if not (qpos_diff < _EPSILON).all():
        return False
    return True

  def _score_and_update_all_targets(self) -> float:
    """Returns the combined score of all targets and updates their states."""
    total = 0.0
    all_done = True
    for target_info, target_state in self._targets:
      if target_state.done:
        total += 1.0
        continue
      # For each target, the arm that has the highest score with it determines
      # the score for the target.
      highest_target_score = 0.0
      for robot_id, robot in enumerate(self._robots):
        # If a robot is dwelling it cannot solve another target or earn shaped
        # reward.
        if self._dwell_steps_left_by_robot[robot_id] > 0:
          continue
        tcp = self._world.GetRobotTcpTransform(robot)
        distance_score = target.distance_score(
            tcp_pose=tcp,
            target_info=target_info,
            config=self._planning_config.target_scoring_config,
        )
        orientation_score = target.orientation_score(
            tcp_pose=tcp,
            target_info=target_info,
            config=self._planning_config.target_scoring_config,
        )
        mixed_score = target.mixed_score(
            dist_score=distance_score,
            ori_score=orientation_score,
            config=self._planning_config.target_scoring_config,
        )
        highest_target_score = max(highest_target_score, mixed_score)
        if target.in_solution_threshold(
            tcp_pose=tcp,
            target_info=target_info,
            config=self._planning_config.target_scoring_config,
        ):
          target_state.done = True
          target_state.robot = robot
          self._dwell_steps_left_by_robot[robot_id] = self._dwell_steps
          break
      if not target_state.done:
        all_done = False
      total += 1.0 if target_state.done else highest_target_score

    mean_target_score = total / len(self._targets)

    # The score consists of two weighted parts - the mean target score and the
    # return to start score. The return to start part is only activated once all
    # targets are done.
    return_to_start_weight = self._planning_config.return_to_start_reward_weight
    target_score_weight = 1.0 - return_to_start_weight
    total_score = target_score_weight * mean_target_score
    if all_done:
      return_to_start_score = self._return_to_start_score()
      total_score += return_to_start_weight * return_to_start_score
    return total_score

  def total_collision_penalty(self) -> float:
    return self._total_collision_penalty

  def total_collision_robot_steps(self) -> int:
    return self._total_collision_robot_steps

  def reset(self) -> dm_env.TimeStep:
    super().reset_impl()
    self._generated_obstacles = []
    self._targets = []
    self._dwell_steps_left_by_robot = [0] * len(self._robots)

    if self._start_state is not None:
      for target_info in self._start_state.targets:
        self._targets.append((target_info, target.TargetState()))
      new_boxes = []
      for box_info in self._start_state.generated_obstacles:
        new_boxes.append((box_info, self._world.AddBox(box_info.spans)))
      for box_info, obj_id in new_boxes:
        self._world.SetWorldTransform(
            obj_id, _make_pose(box_info.centroid, box_info.rotation)
        )
        self._generated_obstacles.append((obj_id, box_info))
      self.set_joint_configurations(
          self._start_state.initial_joint_configurations
      )
      assert self._start_state.initial_robot_placements.shape[0] == len(
          self._robots
      )
      for idx, robot in enumerate(self._robots):
        self._world.SetWorldTransform(
            robot, self._start_state.initial_robot_placements[idx]
        )
      self._start_state = None
      if self._robots_in_collision():
        raise InvalidStartStateError()
    else:
      if self._planning_config.randomize_robot_placement:
        self._randomly_move_robots()
      # If randomize_robot_placement is false, robots will remain at their
      # default positions as defined in the MJCF world file.
      if self._planning_config.starting_joint_config:
        self.set_joint_configurations(
            np.asarray(self._planning_config.starting_joint_config)
        )
      assert not self._robots_in_collision()

      self._sample_and_add_boxes()

      # Do all the AddBox first before SetWorldTransform (this is much faster
      # on MuJoCo before we fix the recompile caching issue).
      new_boxes = [self._world.AddBox(bb.spans)
                   for bb in self._static_obstacles]

      for new_box, bb in zip(new_boxes, self._static_obstacles):
        self._world.SetWorldTransform(
            new_box, _make_pose(bb.centroid, bb.rotation)
        )
        self._generated_obstacles.append((new_box, bb))
      self._sample_and_add_target()
      for target_info in self._planning_config.fixed_targets:
        self._targets.append((target_info, target.TargetState()))

    self._current_score = 0.0
    self._total_collision_penalty = 0.0
    self._total_collision_robot_steps = 0
    self._total_mean_acceleration = 0.0
    self._total_acceleration_cost = 0.0

    return dm_env.restart(self.observation())

  def _collision_penalty(self) -> float:
    """Returns a penalty for each robot in collision."""
    step_max_penalty_per_robot = 1.0 / self._max_steps / len(self._robots)
    return (
        self._planning_config.collision_penalty_scaling
        * step_max_penalty_per_robot
        * len(self._robots_in_collision_last_step)
    )

  def step(
      self, action: np.ndarray, post_action_robot_obs: ArrayTree | None = None
  ) -> dm_env.TimeStep:
    """Makes an environment step (see dm_env for semantics).

    Args:
      action: action to be taken.
      post_action_robot_obs: optional observations after the action. If we
        already have observations after the action (eg. we are replaying an
        episode), supplying the post-action observation here allows us to skip
        the collision checking, making the apply action much faster.

    Returns:
      Timestep.
    """
    if self.terminal():
      return self.reset()

    # Freeze arms that are dwelling.
    for robot_id, _ in enumerate(self._robots):
      if self._dwell_steps_left_by_robot[robot_id] > 0:
        action[robot_id, :] = 0.0
        self._dwell_steps_left_by_robot[robot_id] -= 1

    # If all targets are done, we are in return-to-start mode. In that case we
    # look for arms that are already close to start pose, and take over
    # driving them directly to the start config.
    if all([state.done for _, state in self._targets]):
      threshold = (
          self._planning_config.return_to_start_joint_config_diff_threshold
      )
      for robot_id, (robot, start_jnt_config) in enumerate(
          zip(self._robots, self._start_joint_config)
      ):
        qpos = self._world.GetJointValues(robot)
        qpos_diff = start_jnt_config - qpos
        if (np.abs(qpos_diff) < threshold).all():
          # Take over driving this robot. Calculate the joint velocity we need
          # to drive it to the start config in one timestep (step_impl() below
          # will take care of the acceleration/velocity clamping).
          action[robot_id, :] = (
              qpos_diff / self._planning_config.base_config.timestep_s
          )

    velocities_before = self._current_joint_velocities
    super().step_impl(action, post_action_robot_obs)

    new_score = self._score_and_update_all_targets()
    collision_penalty = self._collision_penalty()

    # Here we are using actual acceleration after all adjustments have been
    # applied (stopping on collision, acceleration clamping,
    # joint limit clamping, etc.)
    timestep = self._planning_config.base_config.timestep_s
    acceleration = (
        self._current_joint_velocities - velocities_before
    ) / timestep
    mean_acc2 = np.mean(np.square(acceleration))
    acceleration_cost_coeff = self._planning_config.acceleration_cost / len(
        self._targets
    )
    acceleration_cost = acceleration_cost_coeff * mean_acc2 * timestep
    reward = float(
        new_score - self._current_score - collision_penalty - acceleration_cost
    )
    self._total_collision_penalty += collision_penalty
    self._total_collision_robot_steps += len(
        self._robots_in_collision_last_step
    )
    self._total_mean_acceleration += np.mean(np.abs(acceleration)) * timestep
    self._total_acceleration_cost += acceleration_cost
    self._current_score = new_score
    if self.terminal():
      return dm_env.termination(reward=reward, observation=self.observation())
    else:
      return dm_env.transition(reward=reward, observation=self.observation())

  def total_acceleration(self) -> float:
    """Total mean acceleration incurred so far in this episode."""
    return self._total_mean_acceleration

  def current_score(self) -> float:
    return self._current_score

  def num_targets_done(self) -> int:
    return sum([state.done for _, state in self._targets])

  def target_states(self) -> list[target.TargetState]:
    return [copy.deepcopy(state) for _, state in self._targets]

  def terminal(self) -> bool:
    """Returns whether the current environment step is terminal."""
    # First check if we are at timeout (terminal in the base class).
    if super().terminal():
      return True

    # If there are targets that aren't done, we are not terminal.
    if not all([state.done for _, state in self._targets]):
      return False

    # If any arm is still dwelling, we are not terminal.
    if any(self._dwell_steps_left_by_robot):
      return False

    # Are we returning to start? If not, we are done.
    if not self._planning_config.return_to_start_required:
      return True
    else:
      # Otherwise we are done if all arms are parked.
      return self._all_arms_are_parked()

  def observation_spec(self) -> SpecTree:
    """Returns observation specifications."""
    total_num_obstacles = self._planning_config.num_obstacles_to_generate + len(
        self._static_obstacles
    )
    obstacle_features = {
        'spans': specs.BoundedArray(
            dtype=np.float32,
            shape=(total_num_obstacles, 3),
            minimum=-base_env.WORLD_SPAN_M / 2,
            maximum=base_env.WORLD_SPAN_M / 2,
        ),
        'poses': specs.BoundedArray(
            dtype=np.float32,
            shape=(total_num_obstacles, 4, 4),
            minimum=base_env.POSE_BOUNDS_MIN,
            maximum=base_env.POSE_BOUNDS_MAX,
        ),
    }
    target_features = {
        'poses': dm_env.specs.BoundedArray(
            dtype=np.float32,
            shape=(self._planning_config.num_targets_to_generate, 4, 4),
            minimum=base_env.POSE_BOUNDS_MIN,
            maximum=base_env.POSE_BOUNDS_MAX,
        ),
        'done': dm_env.specs.BoundedArray(
            dtype=bool,
            shape=(self._planning_config.num_targets_to_generate,),
            minimum=False,
            maximum=True,
        ),
    }
    base_observation_spec = super().observation_spec()
    base_observation_spec['robots']['dwelling'] = specs.BoundedArray(
        dtype=np.float32,
        shape=(len(self._robots),),
        minimum=0.0,
        maximum=1.0,
    )
    return {
        **base_observation_spec,
        'obstacles': obstacle_features,
        'targets': target_features,
        'current_score': specs.BoundedArray(
            dtype=np.float32,
            shape=(),
            minimum=0.0,
            maximum=1.0,
        ),
    }

  def observation(self) -> ArrayTree:
    """Returns the current environment observations."""
    obstacle_features = np.zeros((0, 0))
    if self._generated_obstacles:
      if self._planning_config.augment_obstacle_observations:
        obstacles = [
            box_info.get_augmentation(random.randint(0, 3))
            for _, box_info in self._generated_obstacles
        ]
      else:
        obstacles = list(zip(*self._generated_obstacles))[1]
      (spans, centroids, rotations) = zip(
          *((b.spans, b.centroid, b.rotation) for b in obstacles)
      )
      obstacle_features = {
          'spans': np.asarray(spans, dtype=np.float32),
          'poses': _make_pose(
              np.asarray(centroids, dtype=np.float32),
              np.asarray(rotations, dtype=np.float32),
          ),
      }
    if not self._targets:
      raise ValueError(
          'We have no targets? Are we trying to call this from base_env?'
      )
    (positions, rotations, dones) = zip(
        *((t.position, t.rotation, s.done) for t, s in self._targets)
    )
    # To support position-only targets, encode the orientation as eye(3).
    rotations = [r if r is not None else np.eye(3) for r in rotations]
    for i, _ in enumerate(rotations):
      if rotations[i] is None:
        rotations[i] = np.eye(3)
    target_features = {
        'poses': _make_pose(
            np.asarray(positions, dtype=np.float32),
            np.asarray(rotations, dtype=np.float32),
        ),
        'done': np.asarray(dones, dtype=bool),
    }
    base_observations = super().observation()
    if self._dwell_steps > 0:
      base_observations['robots']['dwelling'] = (
          np.asarray(self._dwell_steps_left_by_robot, dtype=np.float32)
          / self._dwell_steps
      )
    else:
      base_observations['robots']['dwelling'] = np.zeros(
          (len(self._robots),), dtype=np.float32
      )
    return {
        **base_observations,
        'obstacles': obstacle_features,
        'targets': target_features,
        'current_score': np.asarray(self._current_score, dtype=np.float32),
    }

  def get_start_state(self) -> StartState:
    """Returns a proto that allows constructing an identical environment."""
    if not self._targets:
      raise ValueError('get_start_state can only be called after reset()')
    (target_infos, _) = zip(*self._targets)
    placements = np.zeros((len(self._robots), 4, 4), dtype=np.float32)
    for idx, robot in enumerate(self._robots):
      placements[idx] = self._world.GetWorldTransform(robot)

    return StartState(
        generated_obstacles=list(zip(*self._generated_obstacles))[1],
        targets=list(target_infos),
        initial_joint_configurations=self.joint_configurations(),
        initial_robot_placements=placements,
    )
